services:
  api:
    build: ./todo-api
    ports:
      - "5000:5000"
    env_file:
      - ./todo-api/.env
    restart: unless-stopped

  frontend:
    build: ./todo-frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped
